"""empty message

Revision ID: 56932a434d0a
Revises: None
Create Date: 2015-01-24 09:16:10.743951

"""

# revision identifiers, used by Alembic.
revision = '56932a434d0a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('url', sa.String(length=160), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'url')
    ### end Alembic commands ###
